name: Docker Image Publish

on:
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  # Use GitHub Registry for Docker Hub
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  DOCKERFILE: ./docker/Dockerfile


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Create a .env file 
        run: |
          touch ./.env
          echo "$ {{ secrets.ENV_FILE }}  " | base64 --decode
          ls -la
          cat ./.env

      - name: Build and push Docker image
        run: |
          docker login --username ${{ github.actor }} --password ${{secrets.GH_PAT}} ${{ env.REGISTRY }}
          docker build . -t ${{ github.repository }}:latest -f ${{ env.DOCKERFILE }}
          docker push ${{ github.repository }}:latest
